// <auto-generated />
using System;
using MH.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MH.DAL.Migrations
{
    [DbContext(typeof(MyHotelContext))]
    [Migration("20260427072500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MH.Domain.entities.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.Luong", b =>
                {
                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PhuCap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TienLamThemGio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasIndex(new[] { "MaChucVu" }, "IX_Luong");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.Nhanvien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK_nhanvien");

                    b.ToTable("Nhanvien", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoai");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaChucVu");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.ThuePhong", b =>
                {
                    b.Property<int>("MaPhieuThue")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("GioCheckIn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("GioCheckOut")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("GioCheckOutThucTe")
                        .HasColumnType("datetime");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoNguoiO")
                        .HasColumnType("int");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieuThue")
                        .HasName("PK_ThuPhong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhong");

                    b.ToTable("ThuePhong", (string)null);
                });

            modelBuilder.Entity("MH.Domain.entities.Luong", b =>
                {
                    b.HasOne("MH.Domain.entities.ChucVu", "MaChucVuNavigation")
                        .WithMany()
                        .HasForeignKey("MaChucVu")
                        .IsRequired()
                        .HasConstraintName("FK_Luong_ChucVu");

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("MH.Domain.entities.Phong", b =>
                {
                    b.HasOne("MH.Domain.entities.LoaiPhong", "MaLoaiNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK_Phong_LoaiPhong");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("MH.Domain.entities.TaiKhoan", b =>
                {
                    b.HasOne("MH.Domain.entities.ChucVu", "MaChucVuNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK_MaChucVu");

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("MH.Domain.entities.ThuePhong", b =>
                {
                    b.HasOne("MH.Domain.entities.KhachHang", "MaKhachHangNavigation")
                        .WithMany("ThuePhongs")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("makhachhang");

                    b.HasOne("MH.Domain.entities.Nhanvien", "MaNhanVienNavigation")
                        .WithMany("ThuePhongs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("fk_manhanvien");

                    b.HasOne("MH.Domain.entities.Phong", "MaPhongNavigation")
                        .WithMany("ThuePhongs")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("maphong");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("MH.Domain.entities.ChucVu", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("MH.Domain.entities.KhachHang", b =>
                {
                    b.Navigation("ThuePhongs");
                });

            modelBuilder.Entity("MH.Domain.entities.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("MH.Domain.entities.Nhanvien", b =>
                {
                    b.Navigation("ThuePhongs");
                });

            modelBuilder.Entity("MH.Domain.entities.Phong", b =>
                {
                    b.Navigation("ThuePhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
